### ISSUE TITLE
Add tests for the functions

### ISSUE THREAD

**Issue by ugnelis** [ugnelis/tensorflow-rnn-ctc#1]
Add tests for train.py function:

- [x] read_text_file
- [x] make_char_array
- [x] normalize_text
- [x] sparse_tuples_from_sequences
- [x] read_audio_files
- [x] read_text_files
- [x] sequence_decoder
- [x] texts_encoder
- [x] standardize_audios
- [x] get_sequence_lengths
- [x] make_sequences_same_length

**Comment by Edvinas01** [comment]
I'll try to complete this issue

**Comment by ugnelis** [comment]
Okay, thanks

**Comment by ugnelis** [comment]
Pull request #13
