### ISSUE TITLE
sparse representation

### ISSUE THREAD

**Issue by mahi19** [ugnelis/tensorflow-rnn-ctc#19]

**Comment by mahi19** [comment]
Can you please explain why the input vectors are converted into sparse representation specifically, rather than a simple numpy array?

**Comment by ugnelis** [comment]
Sparse tensors are used in `tf.nn.ctc_loss` function. More about `tf.nn.ctc_loss` https://www.tensorflow.org/api_docs/python/tf/nn/ctc_loss.
